services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        - https://api.gisviz.com
        - G-2MY97W2CKX
    env_file:
      - .env.frontend
    container_name: gisviz-frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - gisviz-network

networks:
  gisviz-network:
    external: true