name: Deploy Frontend to IONOS

on:
  push:
    branches:
      - deploy

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Rebuild Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /srv/gisviz/gisviz-frontend
            
            # Pull the latest deploy branch
            git fetch origin deploy
            git reset --hard origin/deploy
            
            # Rebuild and restart the container
            docker compose down
            docker-compose up -d --build